encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.pages, name="pages"),
    path("search/", views.searchpage, name="search"),
    path("new/", views.newentry, name="newentry"),
    path("save/", views.saveentry, name="saveentry"),
    path("edit/", views.editpage, name="edit"),
    path("change/", views.savechanges, name="savechange"),
    path("random/", views.randompage, name="random"),
    path("delete/", views.delete, name="delete")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.core.files.storage import default_storage
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
import markdown2
from django.urls import reverse
from django import forms
import random, os

from . import util

class SearchForm(forms.Form):
    Search_Wiki = forms.CharField()

def index(request):
    """returns index page"""
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })


def pages(request, title):
    """
    Renders the requested wepage
    takes title as an arguement to display that particular page
    """
    #fetch list of lowercase entries to check if the requested title is available or not
    entries = [page.lower() for page in util.list_entries()]

    if title.lower() in entries:
        file = util.get_entry(title)
        #convert the fetched .md file to html file
        htmlfile = markdown2.markdown(file)
        return render(request, "encyclopedia/pages.html", {
            "title": title,
            "body": htmlfile,
        })
    else:
        return render(request, "encyclopedia/fnferror.html") #file not found error

def searchpage(request):
    """
    Searches the local storage for existing markdown/entry files and lists them
    typical search function
    """

    #fetch keyword from search box
    keyword = request.POST.get("q", "")
    #list of existing entries in lower case to look for search item
    valid_entries = [page.lower() for page in util.list_entries()]

    # if whole keyword is exists in the entries then render that page
    if keyword.lower() in valid_entries:
        index = valid_entries.index(keyword.lower())
        return redirect("wiki:pages", util.list_entries()[index])
    #else check if the keyword is a substring of the available entries
    else:
        found_entries = []
        for entry in util.list_entries():
            if keyword.lower() in entry.lower(): found_entries.append(entry)
        return render(request, "encyclopedia/search.html", {
            "entries": found_entries
        })

def newentry(request):
    """renders a new entry form page"""
    return render(request, "encyclopedia/newentry.html")

def saveentry(request):
    """Used to save a post in the local storage when save entry button is clicked"""
    title = request.POST.get("t", "")
    content = request.POST.get("content","")
    #check if the articles with same name already exists
    if title.lower() in [entry.lower() for entry in util.list_entries()]:
        return HttpResponse("Cannot save page. Page already exists")
    #create new file with name as the title of the page
    with open(f"entries/{title}.md", "w") as file:
        file.write(content)
    return redirect("wiki:pages", title)

def editpage(request):
    """Used to edit the existing webpage"""
    #fetch the title of the page to open file
    title = request.POST.get("title", "")
    with open(f"entries/{title}.md", "r") as readfile:
        content = readfile.read()
    
    return render(request, "encyclopedia/editpage.html", {"content": content, "title": title})

def savechanges(request):
    """Save the changes made to the webpage"""
    #get title from the webpage
    title = request.POST.get("title", "")
    #get updated from the page
    content = request.POST.get("editedContent", "")
    #save the webpage in local storage
    util.save_entry(title, content)
    return redirect("wiki:pages", title)
    
def randompage(request):
    #select a random page
    title = random.choice(util.list_entries())
    return redirect("wiki:pages", title)

def delete(request):
    """Delete an existing page"""
    #get title from the webpage
    title = request.POST.get("title", "")
    #if the file exist in entries delete that file
    filename = f"entries/{title}.md"
    if default_storage.exists(filename):
        default_storage.delete(filename)
    return HttpResponseRedirect(reverse("wiki:index"))

encyclopedia/templates/encyclopedia/editpage.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} Edit page {% endblock %}

{% block body %}
    <h2>Edit Post</h2>
    <hr>
    <form action="{% url 'wiki:savechange' %}" method="post" class="mt-5 ml-4">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{title}}" class="form-control">
        <textarea name="editedContent" id="edit" rows="30" class="form-control w-75">{{content}}</textarea>

        <button type="submit" class="btn btn-primary mt-3">Save Changes</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/fnferror.html
{% extends 'encyclopedia/layout.html' %}


{% block title %} File not found {% endblock %}

{% block body %} <h3>Error! Requested page not found</h3> {% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="/wiki/{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search form-control mb-2 p-1" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newentry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">
                        Random Page
                    </a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newentry.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}Wiki-New Article{% endblock %}

{% block body %}
    <h2>Create a new wiki page</h2>
    <hr>
    <form action="{% url 'wiki:saveentry' %}" method="post">
        {%csrf_token%}
        <div>

            <input type="text" name="t" placeholder="Enter title" class="form-control mb-4 w-25">
        </div>
        <textarea name="content" id="content" cols="30" rows="20" class="form-control w-75"></textarea>
        <button type="submit" class="btn btn-primary mt-3">Add to wiki</button>
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/pages.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} {{ title }} {% endblock %}

{% block body %}
    <div class="p-4">
        <div style="height: 40em;">
            {{ body | safe }}
        </div>
    <div></div>
    <form action="{% url 'wiki:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}" >
        <button type="submit" class="btn btn-warning">Edit Post</button>
    </form>
    <form action="{% url 'wiki:delete' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}" >
        <button type="submit" class="btn btn-danger mt-3">Delete Post</button>
    </form>
    </div>


{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block title %} Search {% endblock %}

{% block body %}
    {% for entry in entries %}
        <ul>
            <li><a href="{% url 'wiki:pages' entry%}">{{entry}}</a></li>
        </ul>
    {% endfor %}
{% endblock %}